name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: ovary-syndrome-prediction-app

on:
  push:
    branches:
      - main

permissions:
  contents: "read"
  packages: "write"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: pospacr01.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t pospacr01.azurecr.io/${{ env.AZURE_WEBAPP_NAME}}:${{ github.sha }}
          docker push pospacr01.azurecr.io/${{env.AZURE_WEBAPP_NAME}}:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "pospacr01.azurecr.io/${{env.AZURE_WEBAPP_NAME}}:${{ github.sha }}"
